ALTER TABLE "audit_events" DROP CONSTRAINT "audit_events_event_type_valid";
--> statement-breakpoint
ALTER TABLE "audit_events" ADD CONSTRAINT "audit_events_event_type_valid" CHECK ("audit_events"."event_type" IN (
	'WEBHOOK_RECEIVED',
	'WEBHOOK_REJECTED',
	'WEBHOOK_DUPLICATE',
	'WEBHOOK_CONFLICT',
	'PAYMENT_STATE_CHANGED',
	'WEBHOOK_DELAYED',
	'RETRY_SCHEDULED',
	'RETRY_ATTEMPTED',
	'RETRY_SUCCEEDED',
	'RETRY_DEAD_LETTERED',
	'EXCEPTION_DETECTED',
	'EXCEPTION_STATUS_CHANGED',
	'WEBHOOK_CONFLICT_DETECTED',
	'INVALID_TRANSITION_DETECTED',
	'RETRY_EXHAUSTED',
	'INVESTIGATION_RECORDED'
));
