export const AUDIT_REASON = {
  ACCEPTED: "ACCEPTED",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  MISSING_SIGNATURE: "MISSING_SIGNATURE",
  MALFORMED_SIGNATURE: "MALFORMED_SIGNATURE",
  EXPIRED_SIGNATURE: "EXPIRED_SIGNATURE",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  UNSUPPORTED_PROVIDER: "UNSUPPORTED_PROVIDER",
  UNSUPPORTED_EVENT: "UNSUPPORTED_EVENT",
  DUPLICATE_EVENT: "DUPLICATE_EVENT",
  CONFLICTING_EVENT: "CONFLICTING_EVENT",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  OUT_OF_ORDER: "OUT_OF_ORDER",
  AWAITING_PREREQUISITE: "AWAITING_PREREQUISITE",
  TEMPORARY_PROCESSING_FAILURE: "TEMPORARY_PROCESSING_FAILURE",
  MAX_RETRIES_EXCEEDED: "MAX_RETRIES_EXCEEDED",
  PERMANENT_CONFLICT: "PERMANENT_CONFLICT",
  ALREADY_PROCESSED: "ALREADY_PROCESSED",
  INVALID_NORMALIZED_EVENT: "INVALID_NORMALIZED_EVENT",
  MISSING_EXTERNAL_ID: "MISSING_EXTERNAL_ID",
  MISSING_PAYMENT_ID: "MISSING_PAYMENT_ID",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_CURRENCY: "INVALID_CURRENCY",
  INVALID_TIMESTAMP: "INVALID_TIMESTAMP",
  MATERIAL_CONFLICT: "MATERIAL_CONFLICT",
  IMPOSSIBLE_AFTER_ORDERING: "IMPOSSIBLE_AFTER_ORDERING",
} as const;

export type AuditReason = (typeof AUDIT_REASON)[keyof typeof AUDIT_REASON];

const REASON_PATTERN = /^[A-Z][A-Z0-9_]{0,63}$/;

export function isAuditReasonCode(value: string): boolean {
  return REASON_PATTERN.test(value);
}

export function auditReasonCode(value: string): string {
  if (isAuditReasonCode(value)) {
    return value;
  }
  return AUDIT_REASON.TEMPORARY_PROCESSING_FAILURE;
}
