import { vi } from "vitest";
import type { HookxApi } from "../api/client";
import type {
  FailureLabCatalog,
  FailureLabResetResult,
  FailureLabRunReport,
  GoldenDemoRun,
  MetricsSummary,
  PublicAuditEvent,
  PublicException,
  PublicIncident,
  PublicIncidentTimelineItem,
  PublicInvestigation,
  PublicPayment,
  PublicPaymentListItem,
  PublicRetry,
  PublicWebhookEvent,
} from "../api/types";

export const EXCEPTION_ID = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
export const WEBHOOK_ID = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
export const CAPTURE_WEBHOOK_ID = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";
export const AUTH_WEBHOOK_ID = "99999999-9999-4999-8999-999999999999";
export const PAYMENT_ID = "SYNTHETIC:pay:ui-console";

export const sampleException = {
  exceptionId: EXCEPTION_ID,
  exceptionCode: "CONFLICTING_EVENT",
  severity: "ERROR",
  paymentId: PAYMENT_ID,
  webhookEventId: WEBHOOK_ID,
  provider: "SYNTHETIC",
  status: "OPEN",
  reason: "CONFLICTING_EVENT",
  detectedAt: "2026-01-15T14:02:18.000Z",
  correlationId: "corr-ui-1",
  metadata: { originalAuthoritative: true },
} as unknown as PublicException;

export const retryException: PublicException = {
  ...sampleException,
  exceptionId: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  exceptionCode: "PROCESSING_FAILURE",
  severity: "ERROR",
  reason: "PROCESSING_FAILURE",
};

export const sampleIncident: PublicIncident = {
  incidentId: EXCEPTION_ID,
  exceptionId: EXCEPTION_ID,
  exceptionCode: "CONFLICTING_EVENT",
  severity: "ERROR",
  status: "OPEN",
  paymentId: PAYMENT_ID,
  eventId: WEBHOOK_ID,
  correlationId: "corr-ui-1",
  provider: "SYNTHETIC",
  detectedAt: "2026-01-15T14:02:18.000Z",
  reason: "CONFLICTING_EVENT",
  synthetic: true,
};

export const sampleIncidentTimeline: readonly PublicIncidentTimelineItem[] = [
  {
    seq: 0,
    clock: "2026-01-15T14:02:11.000Z",
    eventTime: "2026-01-15T14:02:11.000Z",
    receivedTime: "2026-01-15T14:02:11.100Z",
    processedTime: null,
    lifecycle: "WEBHOOK_RECEIVED",
    decision: "ACCEPTED",
    reason: "ACCEPTED",
    correlationId: "corr-ui-1",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    eventId: WEBHOOK_ID,
    exceptionId: null,
    exceptionCode: null,
    previousState: null,
    resultingState: null,
    source: "AUDIT",
    sourceId: "audit-received",
    inferred: false,
    synthetic: true,
    retry: null,
    replay: null,
  },
  {
    seq: 1,
    clock: "2026-01-15T14:02:11.000Z",
    eventTime: "2026-01-15T14:02:11.000Z",
    receivedTime: "2026-01-15T14:02:11.100Z",
    processedTime: null,
    lifecycle: "SIGNATURE_VERIFIED",
    decision: "VERIFIED",
    reason: "ACCEPTED",
    correlationId: "corr-ui-1",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    eventId: WEBHOOK_ID,
    exceptionId: null,
    exceptionCode: null,
    previousState: null,
    resultingState: null,
    source: "AUDIT",
    sourceId: "audit-received",
    inferred: true,
    synthetic: true,
    retry: null,
    replay: null,
  },
  {
    seq: 2,
    clock: "2026-01-15T14:02:11.000Z",
    eventTime: "2026-01-15T14:02:11.000Z",
    receivedTime: "2026-01-15T14:02:11.100Z",
    processedTime: null,
    lifecycle: "EVENT_PERSISTED",
    decision: "ACCEPTED",
    reason: "ACCEPTED",
    correlationId: "corr-ui-1",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    eventId: WEBHOOK_ID,
    exceptionId: null,
    exceptionCode: null,
    previousState: null,
    resultingState: null,
    source: "AUDIT",
    sourceId: "audit-received",
    inferred: true,
    synthetic: true,
    retry: null,
    replay: null,
  },
  {
    seq: 3,
    clock: "2026-01-15T14:02:12.000Z",
    eventTime: "2026-01-15T14:02:11.000Z",
    receivedTime: "2026-01-15T14:02:11.100Z",
    processedTime: null,
    lifecycle: "CONFLICT_DETECTED",
    decision: "CONFLICTING_EVENT",
    reason: "CONFLICTING_EVENT",
    correlationId: "corr-ui-1",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    eventId: WEBHOOK_ID,
    exceptionId: EXCEPTION_ID,
    exceptionCode: "CONFLICTING_EVENT",
    previousState: null,
    resultingState: null,
    source: "AUDIT",
    sourceId: "audit-conflict",
    inferred: false,
    synthetic: true,
    retry: null,
    replay: null,
  },
  {
    seq: 4,
    clock: "2026-01-15T14:02:12.000Z",
    eventTime: "2026-01-15T14:02:11.000Z",
    receivedTime: "2026-01-15T14:02:11.100Z",
    processedTime: null,
    lifecycle: "EXCEPTION_CREATED",
    decision: "CONFLICTING_EVENT",
    reason: "CONFLICTING_EVENT",
    correlationId: "corr-ui-1",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    eventId: WEBHOOK_ID,
    exceptionId: EXCEPTION_ID,
    exceptionCode: "CONFLICTING_EVENT",
    previousState: null,
    resultingState: null,
    source: "EXCEPTION",
    sourceId: EXCEPTION_ID,
    inferred: false,
    synthetic: true,
    retry: null,
    replay: null,
  },
  {
    seq: 5,
    clock: "2026-01-15T14:02:15.000Z",
    eventTime: null,
    receivedTime: null,
    processedTime: "2026-01-15T14:02:15.000Z",
    lifecycle: "INVESTIGATION_AVAILABLE",
    decision: null,
    reason: null,
    correlationId: "corr-ui-invest",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    eventId: WEBHOOK_ID,
    exceptionId: EXCEPTION_ID,
    exceptionCode: "CONFLICTING_EVENT",
    previousState: null,
    resultingState: null,
    source: "INVESTIGATION",
    sourceId: "22222222-2222-4222-8222-222222222222",
    inferred: false,
    synthetic: true,
    retry: null,
    replay: null,
  },
];

export const retryIncidentTimeline: readonly PublicIncidentTimelineItem[] = [
  {
    ...sampleIncidentTimeline[0]!,
    seq: 0,
    lifecycle: "RETRY_SCHEDULED",
    retry: {
      attempt: 1,
      scheduledAt: "2026-01-15T14:03:18.000Z",
      attemptedAt: null,
      result: "TEMPORARY_PROCESSING_FAILURE",
      failureClass: "RETRYABLE",
    },
  },
  {
    ...sampleIncidentTimeline[0]!,
    seq: 1,
    clock: "2026-01-15T14:03:18.000Z",
    lifecycle: "RETRY_ATTEMPTED",
    retry: {
      attempt: 2,
      scheduledAt: null,
      attemptedAt: "2026-01-15T14:03:18.000Z",
      result: "TEMPORARY_PROCESSING_FAILURE",
      failureClass: "RETRYABLE",
    },
    replay: null,
  },
];

export const replayIncidentTimeline: readonly PublicIncidentTimelineItem[] = [
  {
    ...sampleIncidentTimeline[0]!,
    seq: 0,
    lifecycle: "REPLAY_STARTED",
    replay: {
      replayId: "replay-1",
      trigger: "OUT_OF_ORDER",
      eventsConsidered: 3,
      previousState: "CREATED",
      resultingState: "CREATED",
    },
  },
  {
    ...sampleIncidentTimeline[0]!,
    seq: 1,
    clock: "2026-01-15T14:02:15.400Z",
    lifecycle: "REPLAY_COMPLETED",
    previousState: "AUTHORIZED",
    resultingState: "CAPTURED",
    replay: {
      replayId: "replay-2",
      trigger: "OUT_OF_ORDER",
      eventsConsidered: 3,
      previousState: "AUTHORIZED",
      resultingState: "CAPTURED",
    },
  },
];

export const samplePayment: PublicPayment = {
  provider: "SYNTHETIC",
  paymentId: PAYMENT_ID,
  state: "CAPTURED",
  amountMinor: "10000",
  currency: "INR",
  createdAt: "2026-01-15T14:02:11.000Z",
  lastOccurredAt: "2026-01-15T14:02:18.000Z",
  updatedAt: "2026-01-15T14:02:18.000Z",
};

export const samplePaymentListItem: PublicPaymentListItem = {
  ...samplePayment,
  exceptionCount: 1,
};

export const sampleWebhooks: readonly PublicWebhookEvent[] = [
  {
    webhookEventId: WEBHOOK_ID,
    provider: "SYNTHETIC",
    externalEventId: "SYNTHETIC:evt:ui-created",
    paymentId: PAYMENT_ID,
    eventType: "payment.created",
    occurredAt: "2026-01-15T14:02:11.000Z",
    receivedAt: "2026-01-15T14:02:11.100Z",
    amountMinor: "10000",
    currency: "INR",
    processingStatus: "PROCESSED",
    deliveryAttempt: 1,
  },
  {
    webhookEventId: CAPTURE_WEBHOOK_ID,
    provider: "SYNTHETIC",
    externalEventId: "SYNTHETIC:evt:ui-captured",
    paymentId: PAYMENT_ID,
    eventType: "payment.captured",
    occurredAt: "2026-01-15T14:02:14.000Z",
    receivedAt: "2026-01-15T14:02:14.100Z",
    amountMinor: "10000",
    currency: "INR",
    processingStatus: "PROCESSED",
    deliveryAttempt: 1,
  },
];

export const outOfOrderWebhooks: readonly PublicWebhookEvent[] = [
  {
    webhookEventId: WEBHOOK_ID,
    provider: "SYNTHETIC",
    externalEventId: "SYNTHETIC:evt:ui-created",
    paymentId: PAYMENT_ID,
    eventType: "payment.created",
    occurredAt: "2026-01-15T14:02:11.000Z",
    receivedAt: "2026-01-15T14:02:11.100Z",
    amountMinor: "10000",
    currency: "INR",
    processingStatus: "PROCESSED",
    deliveryAttempt: 1,
  },
  {
    webhookEventId: CAPTURE_WEBHOOK_ID,
    provider: "SYNTHETIC",
    externalEventId: "SYNTHETIC:evt:ui-captured",
    paymentId: PAYMENT_ID,
    eventType: "payment.captured",
    occurredAt: "2026-01-15T14:02:14.000Z",
    receivedAt: "2026-01-15T14:02:12.000Z",
    amountMinor: "10000",
    currency: "INR",
    processingStatus: "PROCESSED",
    deliveryAttempt: 1,
  },
  {
    webhookEventId: AUTH_WEBHOOK_ID,
    provider: "SYNTHETIC",
    externalEventId: "SYNTHETIC:evt:ui-authorized",
    paymentId: PAYMENT_ID,
    eventType: "payment.authorized",
    occurredAt: "2026-01-15T14:02:13.000Z",
    receivedAt: "2026-01-15T14:02:15.000Z",
    amountMinor: "10000",
    currency: "INR",
    processingStatus: "PROCESSED",
    deliveryAttempt: 1,
  },
];

export const sampleAudit: readonly PublicAuditEvent[] = [
  {
    auditEventId: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
    eventType: "PAYMENT_STATE_CHANGED",
    occurredAt: "2026-01-15T14:02:11.000Z",
    recordedAt: "2026-01-15T14:02:11.200Z",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    webhookEventId: WEBHOOK_ID,
    previousState: null,
    resultingState: "CREATED",
    actor: "SYSTEM",
    reason: "TRANSITION",
    correlationId: "corr-ui-created",
    metadata: {},
  },
  {
    auditEventId: "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
    eventType: "PAYMENT_STATE_CHANGED",
    occurredAt: "2026-01-15T14:02:13.000Z",
    recordedAt: "2026-01-15T14:02:13.200Z",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    webhookEventId: AUTH_WEBHOOK_ID,
    previousState: "CREATED",
    resultingState: "AUTHORIZED",
    actor: "SYSTEM",
    reason: "TRANSITION",
    correlationId: "corr-ui-authorized",
    metadata: {},
  },
  {
    auditEventId: "ffffffff-ffff-4fff-8fff-ffffffffffff",
    eventType: "WEBHOOK_DELAYED",
    occurredAt: "2026-01-15T14:02:14.000Z",
    recordedAt: "2026-01-15T14:02:14.200Z",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    webhookEventId: CAPTURE_WEBHOOK_ID,
    previousState: "CREATED",
    resultingState: "CREATED",
    actor: "SYSTEM",
    reason: "OUT_OF_ORDER",
    correlationId: "corr-ui-delayed",
    metadata: {},
  },
  {
    auditEventId: "11111111-1111-4111-8111-111111111111",
    eventType: "PAYMENT_STATE_CHANGED",
    occurredAt: "2026-01-15T14:02:18.000Z",
    recordedAt: "2026-01-15T14:02:18.200Z",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    webhookEventId: CAPTURE_WEBHOOK_ID,
    previousState: "AUTHORIZED",
    resultingState: "CAPTURED",
    actor: "SYSTEM",
    reason: "TRANSITION",
    correlationId: "corr-ui-replay",
    metadata: {},
  },
];

export const sampleRetryAudit: readonly PublicAuditEvent[] = [
  {
    auditEventId: "33333333-3333-4333-8333-333333333333",
    eventType: "RETRY_SCHEDULED",
    occurredAt: "2026-01-15T14:02:20.000Z",
    recordedAt: "2026-01-15T14:02:20.000Z",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    webhookEventId: WEBHOOK_ID,
    previousState: null,
    resultingState: null,
    actor: "SYSTEM",
    reason: "TEMPORARY_PROCESSING_FAILURE",
    correlationId: "corr-ui-retry-1",
    metadata: { attempt: 1 },
  },
  {
    auditEventId: "44444444-4444-4444-8444-444444444444",
    eventType: "RETRY_ATTEMPTED",
    occurredAt: "2026-01-15T14:03:18.000Z",
    recordedAt: "2026-01-15T14:03:18.000Z",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    webhookEventId: WEBHOOK_ID,
    previousState: null,
    resultingState: null,
    actor: "SYSTEM",
    reason: "TEMPORARY_PROCESSING_FAILURE",
    correlationId: "corr-ui-retry-2",
    metadata: { attempt: 2 },
  },
  {
    auditEventId: "55555555-5555-4555-8555-555555555555",
    eventType: "RETRY_SUCCEEDED",
    occurredAt: "2026-01-15T14:03:18.100Z",
    recordedAt: "2026-01-15T14:03:18.100Z",
    provider: "SYNTHETIC",
    paymentId: PAYMENT_ID,
    webhookEventId: WEBHOOK_ID,
    previousState: null,
    resultingState: null,
    actor: "SYSTEM",
    reason: "ACCEPTED",
    correlationId: "corr-ui-retry-3",
    metadata: { attempt: 2 },
  },
];

export const sampleRetry: PublicRetry = {
  webhookEventId: WEBHOOK_ID,
  attemptCount: 2,
  maxAttempts: 5,
  status: "PENDING",
  nextAttemptAt: "2026-01-15T14:03:18.000Z",
  lastErrorCode: "TEMPORARY_PROCESSING_FAILURE",
  lastFailedAt: "2026-01-15T14:02:20.000Z",
};

export const sampleInvestigation: PublicInvestigation = {
  investigationId: "22222222-2222-4222-8222-222222222222",
  incidentId: EXCEPTION_ID,
  exceptionId: EXCEPTION_ID,
  investigator: "stub",
  modelId: null,
  promptVersion: "investigation-v2",
  createdAt: "2026-01-15T14:05:00.000Z",
  correlationId: "corr-ui-invest",
  evidenceHash: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  result: {
    summary: "Deterministic conflict classification with no financial mutation.",
    facts: ["Exception remains CONFLICTING_EVENT."],
    evidence: [
      {
        sourceType: "EXCEPTION",
        sourceId: EXCEPTION_ID,
        fact: "Deterministic engine classified CONFLICTING_EVENT.",
      },
      {
        sourceType: "WEBHOOK_EVENT",
        sourceId: WEBHOOK_ID,
        fact: "Stored webhook identity was retained.",
      },
    ],
    incidentType: "CONFLICTING_EVENT",
    severity: "ERROR",
    rootCause: "The provider may have retried the same event identity with a different payload.",
    likelyCause: "The provider may have retried the same event identity with a different payload.",
    impact: "Payment state remained CREATED. No second economic state transition occurred.",
    recommendedActions: [
      {
        code: "INVESTIGATE_CONFLICTING_PAYLOAD",
        detail: "Compare the stored event with the rejected delivery. Do not capture or refund.",
        executable: false,
      },
    ],
    recommendedAction: {
      code: "INVESTIGATE_CONFLICTING_PAYLOAD",
      detail: "Compare the stored event with the rejected delivery. Do not capture or refund.",
      executable: false,
    },
    confidence: "MEDIUM",
    confidenceReason: "Conflict classification is present with a stored webhook identity.",
    limitations: ["Investigation does not change payment state."],
  },
};

export const sampleFailureLabCatalog: FailureLabCatalog = {
  notice: "The Failure Lab never sends real payment requests.",
  synthetic: true,
  scenarios: [
    {
      id: "DUPLICATE_DELIVERY",
      number: "01",
      title: "DUPLICATE DELIVERY",
      explanation:
        "One synthetic webhook is signed once and posted twice through ingest.",
      expected:
        "First delivery accepted, persisted, processed. Second classified duplicate. One state transition.",
      failureMode: "NONE",
    },
    {
      id: "OUT_OF_ORDER",
      number: "02",
      title: "OUT-OF-ORDER DELIVERY",
      explanation: "Created, captured, then authorized.",
      expected: "Capture delayed. Authorization accepted. Replay reaches CAPTURED.",
      failureMode: "NONE",
    },
    {
      id: "CONFLICTING_EVENT",
      number: "03",
      title: "CONFLICTING EVENT",
      explanation: "Same identity, different payload hash.",
      expected: "CONFLICTING_EVENT. Original row unchanged.",
      failureMode: "NONE",
    },
    {
      id: "TRANSIENT_FAILURE",
      number: "04",
      title: "TRANSIENT FAILURE",
      explanation:
        "A signed synthetic payment webhook is delivered through ingest. Lab-only FAIL_ONCE injection causes the first processing attempt to fail.",
      expected:
        "HOOKX verifies, normalizes, and persists the event; records the failure; schedules a retry; retries; recovers payment state.",
      failureMode: "FAIL_ONCE",
      architectureDemo: true,
    },
    {
      id: "RETRY_EXHAUSTION",
      number: "05",
      title: "RETRY EXHAUSTION",
      explanation: "Lab-only ALWAYS_FAIL injection.",
      expected: "Retries continue until max attempts, then dead-letter.",
      failureMode: "ALWAYS_FAIL",
    },
    {
      id: "REPLAY_RECOVERY",
      number: "06",
      title: "REPLAY RECOVERY",
      explanation: "Capture arrives before authorization.",
      expected: "REPLAY STARTED, delayed capture applied, final CAPTURED.",
      failureMode: "NONE",
    },
    {
      id: "RAZORPAY_SHAPED_DUPLICATE",
      number: "07",
      title: "RAZORPAY-SHAPED DUPLICATE",
      explanation:
        "A synthetic Razorpay payment.authorized envelope is signed and posted twice through POST /webhooks/razorpay. The Razorpay adapter normalizes it. Data source is SYNTHETIC. Nothing is sent to Razorpay.",
      expected:
        "First delivery accepted and persisted. Second classified duplicate. One stored event. HOOKX does not invent payment.created, so the Razorpay-only stream does not project a payment state.",
      failureMode: "NONE",
    },
    {
      id: "GOLDEN_DEMO",
      number: "08",
      title: "GOLDEN DEMO",
      explanation:
        "A synthetic Razorpay payment.authorized envelope is posted through POST /webhooks/razorpay. Lab-only FAIL_ONCE injection fails the first processing attempt.",
      expected:
        "Signature verified. One stored event. First processing fails. Retry succeeds. Redelivery is duplicate.",
      failureMode: "FAIL_ONCE",
      goldenDemo: true,
    },
  ],
};

export const sampleFailureLabRun: FailureLabRunReport = {
  runId: "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
  scenario: "DUPLICATE_DELIVERY",
  title: "DUPLICATE DELIVERY",
  synthetic: true,
  demoRun: false,
  labels: ["SYNTHETIC"],
  notice: "The Failure Lab never sends real payment requests.",
  startedAt: "2026-01-15T14:21:03.000Z",
  finishedAt: "2026-01-15T14:21:03.000Z",
  failureMode: "NONE",
  retryPolicy: { maxAttempts: 5, baseDelayMs: 1000, maxDelayMs: 8000 },
  input: {
    deliveries: 2,
    eventOrderSent: ["payment.created", "payment.created"],
    eventTimeOrder: ["payment.created"],
  },
  result: {
    processed: 1,
    duplicate: 1,
    conflict: 0,
    error: 0,
    accepted: 1,
  },
  stateChange: 1,
  payment: {
    provider: "SYNTHETIC",
    paymentId: "SYNTHETIC:pay:lab-eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
    state: "CREATED",
    amountMinor: "10000",
  },
  originalAmountMinor: "10000",
  originalPayloadHash: "SYNTHETIC:hash:lab-dup",
  exception: {
    exceptionId: EXCEPTION_ID,
    exceptionCode: "DUPLICATE_EVENT",
  },
  incidentId: EXCEPTION_ID,
  auditCount: 2,
  retry: null,
  deadLetter: null,
  replay: null,
  log: [
    {
      clock: "2026-01-15T14:21:03.000Z",
      lifecycle: "WEBHOOK_RECEIVED",
      decision: "ACCEPTED",
      inferred: false,
    },
    {
      clock: "2026-01-15T14:21:03.000Z",
      lifecycle: "SIGNATURE_VERIFIED",
      decision: null,
      inferred: false,
    },
    {
      clock: "2026-01-15T14:21:03.000Z",
      lifecycle: "EVENT_PERSISTED",
      decision: null,
      inferred: false,
    },
    {
      clock: "2026-01-15T14:21:03.000Z",
      lifecycle: "PROCESSING_STARTED",
      decision: null,
      inferred: false,
    },
    {
      clock: "2026-01-15T14:21:03.000Z",
      lifecycle: "DUPLICATE_DETECTED",
      decision: "DUPLICATE",
      inferred: false,
    },
  ],
  deliveries: [
    {
      stepIndex: 0,
      eventType: "payment.created",
      eventKey: "created",
      httpStatus: 200,
      bodyStatus: "accepted",
      code: null,
      kind: "SEND",
    },
    {
      stepIndex: 1,
      eventType: "payment.created",
      eventKey: "created",
      httpStatus: 200,
      bodyStatus: "duplicate",
      code: null,
      kind: "RESEND_IDENTICAL",
    },
  ],
  links: {
    incident: `/incidents/${EXCEPTION_ID}`,
    payment: "/payments/SYNTHETIC%3Apay%3Alab-eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee",
    event: `/events/${WEBHOOK_ID}`,
  },
};

const GOLDEN_DEMO_RUN_ID = "ffffffff-ffff-4fff-8fff-ffffffffffff";
const GOLDEN_PAYMENT_ID = `SYNTHETIC:pay:lab-${GOLDEN_DEMO_RUN_ID}`;
const GOLDEN_EVENT_KEY = `SYNTHETIC:evt:lab-${GOLDEN_DEMO_RUN_ID}-1`;
const GOLDEN_CORRELATION = `demo-${GOLDEN_DEMO_RUN_ID}`;

export const sampleGoldenDemoRun: GoldenDemoRun = {
  demoRunId: GOLDEN_DEMO_RUN_ID,
  correlationId: GOLDEN_CORRELATION,
  synthetic: true,
  notice: "This is a synthetic demonstration. Nothing is sent to Razorpay.",
  invariant: {
    storedEventCount: 1,
    stateChange: 0,
    duplicateDeliveries: 1,
    noDuplicateEconomicEffect: true,
  },
  run: {
    runId: GOLDEN_DEMO_RUN_ID,
    scenario: "GOLDEN_DEMO",
    title: "GOLDEN DEMO",
    synthetic: true,
    demoRun: true,
    labels: ["SYNTHETIC", "RAZORPAY ADAPTER", "DEMO RUN"],
    notice: "This is a synthetic demonstration. Nothing is sent to Razorpay.",
    startedAt: "2026-01-15T14:30:00.000Z",
    finishedAt: "2026-01-15T14:30:01.000Z",
    failureMode: "FAIL_ONCE",
    retryPolicy: { maxAttempts: 2, baseDelayMs: 1000, maxDelayMs: 8000 },
    input: {
      deliveries: 2,
      eventOrderSent: ["payment.authorized", "payment.authorized"],
      eventTimeOrder: ["payment.authorized"],
    },
    result: {
      processed: 0,
      duplicate: 1,
      conflict: 0,
      error: 1,
      accepted: 0,
    },
    stateChange: 0,
    payment: {
      provider: "razorpay",
      paymentId: GOLDEN_PAYMENT_ID,
      state: null,
      amountMinor: null,
    },
    originalAmountMinor: "10000",
    originalPayloadHash: "hash-not-a-signature",
    exception: {
      exceptionId: EXCEPTION_ID,
      exceptionCode: "PROCESSING_FAILURE",
    },
    incidentId: EXCEPTION_ID,
    correlationId: GOLDEN_CORRELATION,
    storedEventCount: 1,
    eventProcessingStatus: "PROCESSED",
    eventType: "payment.authorized",
    auditCount: 8,
    retry: {
      attemptCount: 2,
      status: "SUCCEEDED",
      nextAttemptAt: null,
      lastErrorCode: "TEMPORARY_PROCESSING_FAILURE",
      lastFailedAt: "2026-01-15T14:30:00.200Z",
      failureClass: "RETRYABLE",
    },
    deadLetter: null,
    replay: null,
    log: [
      {
        clock: "2026-01-15T14:30:00.000Z",
        lifecycle: "WEBHOOK_RECEIVED",
        decision: "ACCEPTED",
        inferred: false,
      },
      {
        clock: "2026-01-15T14:30:00.050Z",
        lifecycle: "SIGNATURE_VERIFIED",
        decision: null,
        inferred: false,
      },
      {
        clock: "2026-01-15T14:30:00.080Z",
        lifecycle: "WEBHOOK_NORMALIZED",
        decision: null,
        inferred: false,
      },
      {
        clock: "2026-01-15T14:30:00.100Z",
        lifecycle: "EVENT_PERSISTED",
        decision: null,
        inferred: false,
      },
      {
        clock: "2026-01-15T14:30:00.120Z",
        lifecycle: "PROCESSING_STARTED",
        decision: null,
        inferred: false,
      },
      {
        clock: "2026-01-15T14:30:00.200Z",
        lifecycle: "RETRY_SCHEDULED",
        decision: null,
        inferred: false,
      },
      {
        clock: "2026-01-15T14:30:00.400Z",
        lifecycle: "RETRY_ATTEMPTED",
        decision: null,
        inferred: false,
      },
      {
        clock: "2026-01-15T14:30:00.500Z",
        lifecycle: "RETRY_SUCCEEDED",
        decision: null,
        inferred: false,
      },
    ],
    deliveries: [
      {
        stepIndex: 0,
        eventType: "payment.authorized",
        eventKey: GOLDEN_EVENT_KEY,
        httpStatus: 500,
        bodyStatus: "error",
        code: "TEMPORARY_PROCESSING_FAILURE",
        kind: "original",
      },
      {
        stepIndex: 1,
        eventType: "payment.authorized",
        eventKey: GOLDEN_EVENT_KEY,
        httpStatus: 200,
        bodyStatus: "duplicate",
        code: null,
        kind: "redelivery",
      },
    ],
    links: {
      incident: `/incidents/${EXCEPTION_ID}`,
      payment: `/payments/${encodeURIComponent(GOLDEN_PAYMENT_ID)}`,
      event: `/events/${WEBHOOK_ID}`,
    },
  },
};

export const sampleGoldenDemoExhausted: GoldenDemoRun = {
  ...sampleGoldenDemoRun,
  invariant: {
    storedEventCount: 1,
    stateChange: 0,
    duplicateDeliveries: 0,
    noDuplicateEconomicEffect: true,
  },
  run: {
    ...sampleGoldenDemoRun.run,
    result: {
      processed: 0,
      duplicate: 0,
      conflict: 0,
      error: 1,
      accepted: 0,
    },
    eventProcessingStatus: "RECEIVED",
    retry: {
      attemptCount: 2,
      status: "DEAD_LETTERED",
      nextAttemptAt: null,
      lastErrorCode: "TEMPORARY_PROCESSING_FAILURE",
      lastFailedAt: "2026-01-15T14:30:00.800Z",
      failureClass: "RETRYABLE",
    },
    deadLetter: {
      failureCode: "RETRY_EXHAUSTED",
      attemptCount: 2,
      deadLetteredAt: "2026-01-15T14:30:00.900Z",
    },
    exception: {
      exceptionId: EXCEPTION_ID,
      exceptionCode: "RETRY_EXHAUSTED",
    },
    log: sampleGoldenDemoRun.run.log.filter(
      (entry) => entry.lifecycle !== "RETRY_SUCCEEDED",
    ),
  },
};

export const sampleFailureLabReset: FailureLabResetResult = {
  notice: "The Failure Lab never sends real payment requests.",
  deleted: {
    investigations: 0,
    exceptions: 1,
    deadLetters: 0,
    retries: 0,
    audit: 2,
    webhooks: 1,
    payments: 1,
  },
};

export const sampleMetricsEmpty: MetricsSummary = {
  asOf: "2026-01-15T14:00:00.000Z",
  persisted: {
    source: "database",
    webhookEvents: 0,
    exceptions: 0,
    retries: 0,
    deadLetters: 0,
    auditByType: {},
  },
};

export const sampleMetricsPopulated: MetricsSummary = {
  asOf: "2026-01-15T14:00:00.000Z",
  persisted: {
    source: "database",
    webhookEvents: 4,
    exceptions: 2,
    retries: 1,
    deadLetters: 0,
    auditByType: {
      WEBHOOK_DUPLICATE: 1,
      RETRY_SUCCEEDED: 1,
    },
  },
};

export function createMockApi(overrides: Partial<HookxApi> = {}): HookxApi {
  return {
    listExceptions: vi.fn(async () => [sampleException]),
    getException: vi.fn(async () => sampleException),
    listIncidents: vi.fn(async () => [sampleIncident]),
    getIncident: vi.fn(async () => sampleIncident),
    getIncidentTimeline: vi.fn(async () => ({
      incident: sampleIncident,
      timeline: sampleIncidentTimeline,
    })),
    listPayments: vi.fn(async () => [samplePaymentListItem]),
    getPayment: vi.fn(async () => samplePayment),
    listPaymentExceptions: vi.fn(async () => [sampleException]),
    listWebhooks: vi.fn(async () => sampleWebhooks),
    getWebhook: vi.fn(async () => sampleWebhooks[0] ?? null),
    listPaymentWebhooks: vi.fn(async () => sampleWebhooks),
    listPaymentAudit: vi.fn(async () => sampleAudit),
    listWebhookAudit: vi.fn(async () => sampleAudit),
    getRetry: vi.fn(async () => null),
    getDeadLetter: vi.fn(async () => null),
    getInvestigation: vi.fn(async () => null),
    investigate: vi.fn(async () => sampleInvestigation),
    listIncidentInvestigations: vi.fn(async () => []),
    investigateIncident: vi.fn(async () => sampleInvestigation),
    getFailureLabCatalog: vi.fn(async () => sampleFailureLabCatalog),
    runFailureLab: vi.fn(async () => sampleFailureLabRun),
    getFailureLabRun: vi.fn(async () => sampleFailureLabRun),
    resetFailureLab: vi.fn(async () => sampleFailureLabReset),
    getMetricsSummary: vi.fn(async () => sampleMetricsEmpty),
    runGoldenDemo: vi.fn(async () => sampleGoldenDemoRun),
    listGoldenDemoRuns: vi.fn(async () => []),
    getGoldenDemoRun: vi.fn(async () => sampleGoldenDemoRun),
    ...overrides,
  };
}
